version: '3'

services:
  RM-Skills-9-backend:
    image: docker.ergon.ch/berufsbildung/rm-skills-9/backend:latest
    depends_on:
      - RM-Skills-9-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://RM-Skills-9-db:5432/rm-skills-9
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_FLYWAY_URL=jdbc:postgresql://RM-Skills-9-db:5432/rm-skills-9
      - SPRING_FLYWAY_USER=RM-Skills-9
      - SPRING_FLYWAY_PASSWORD=password
    ports:
      - "8000:8080"
    networks:
      - RM-Skills-9-network

  RM-Skills-9-frontend:
    image: docker.ergon.ch/berufsbildung/rm-skills-9/frontend:latest
    depends_on:
      - RM-Skills-9-backend
    ports:
      - "8080:80"
    networks:
      - RM-Skills-9-network

  RM-Skills-9-db:
    image: mariadb:10.9
    environment:
      MARIADB_DATABASE: rm-skills-9
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: password
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"

networks:
  RM-Skills-9-network:
