CREATE TABLE "user"
(
    USER_ID       SERIAL PRIMARY KEY,
    FIRST_NAME    VARCHAR(50) NOT NULL,
    LAST_NAME     VARCHAR(50) NOT NULL,
    EMAIL         VARCHAR(50) NOT NULL UNIQUE,
    RANKING       INT         NOT NULL,
    ADMINISTRATOR BOOLEAN     NOT NULL
);
